### ISSUE TITLE
Project level issue title transformation

### ISSUE THREAD

**Issue by rexim** [tsoding/snitch#103]
Derived from #102 

`.snitch.yaml` at the project root.

```
title:
  transform:
    - match: (.*) \*/
      replace: \1
    - match: (.*) \*\}
      replace: \1
```
